<?php require 'templates/layout/hedader.phtml' ?>
<div class="d-flex flex-row justify-content-center mb-3">
    <div class="w-50 p-5">
        <h2 class="display-6">Iniciar Sesión</h2>
    </div>


<div class="d-flex flex-row justify-content-center">
    <div class="p-2">
        <ul class="navbar-nav d-flex flex-row justify-content-center">
            <div class="card" style="width: 30rem; margin: auto;"> <!-- Ajustado a 30rem para evitar ser demasiado ancho -->

                <form action="autentificación" method="POST" class="p-4"> <!-- Padding para espaciado interno -->


                    <div class="form-floating mb-3">
                        <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com" name="email">
                        <label for="floatingInput">Nombre</label>
                    </div>


                    <div class="form-floating">
                        <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="contrasenea">
                        <label for="floatingPassword">Contraseña</label>
                    </div>

                    <!-- Mostrar error si existe -->
                    <?php if (isset($error) && !empty($error)) : ?>
                        <div class="alert alert-danger d-flex align-items-center mt-3" role="alert">
                            <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:">
                                <use xlink:href="#exclamation-triangle-fill" />
                            </svg>
                            <div>
                                <?= htmlspecialchars($error); ?>
                            </div>
                        </div>
                    <?php endif; ?>

                    <!-- Botón de enviar -->
                    <div class="d-grid mt-3">
                        <button type="submit" class="btn btn-primary mb-3">Iniciar sesión</button>
                    </div>
                </form>

            </div>
        </ul>
    </div>
</div>
</div>
<?php require 'templates/layout/pieDepagina.phtml' ?>