<?php require 'templates/layout/hedader.phtml'; ?>

<div class="container mt-5">
    <h2 class="display-6 text-center mb-4">Detalles del Viaje</h2>

    <div class="card">
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Destino de Inicio:</strong> <?= $viaje->destino_inicio ?></li>
                <li class="list-group-item"><strong>Destino de Llegada:</strong> <?= $viaje->destino_fin ?></li>
                <li class="list-group-item"><strong>Fecha de Salida:</strong> <?= $viaje->fecha_salida ?></li>
                <li class="list-group-item"><strong>Precio:</strong> $<?= $viaje->precio ?> ARS</li>
                <li class="list-group-item"><strong>Pasajeros:</strong> <?= $persona->nombre ?> <?= $persona->apellido ?></li>


                <?php if (!empty($viaje->imagen)): ?> <li class="list-group-item"><strong>imagen:</strong> <img width="400px" src="<?= BASE_URL . $viaje->imagen ?>">
                    <?php endif; ?>


            </ul>
        </div>
    </div>
</div>

<?php require 'templates/layout/pieDepagina.phtml'; ?>