<!-- formulario de alta de tarea -->
<form action="nuevo-viaje" method="POST">
    <div>
        <div>
            <div>
                <label>Destino de inicio</label>
                <input type="text" name="destino_inicio" required>
                
                <label>Destino de fin</label>
                <input type="text" name="destino_fin" required>

                <label>Fecha de viaje</label>
                <input type="date" name="fecha_salida" require>
            </div>
        </div>        
    </div>
    <button type="submit">Guardar</button>
</form>