<?php require 'templates/layout/hedader.phtml' ?>

<div class="w-50 p-5">
    <h2 class="display-6">Detalles:</h2>
    <ul class="list-group">
        <li class="list-group-item">Destino de inicio: <?= $viaje->destino_inicio ?></li>
        <li class="list-group-item">Destino de llegada: <?= $viaje->destino_fin ?> </li>
        <li class="list-group-item">Fecha de salida: <?= $viaje->fecha_salida ?></li>
        <li class="list-group-item">Precio: $<?= $viaje->precio ?> ARS</li>
        <li class="list-group-item"> Pasajeros: <?= $persona->nombre ?> <?= $persona->apellido ?></li>
    </ul>
</div>

<div class="d-flex flex-row justify-content-center">
    <div class="p-2">
        <ul class="navbar-nav d-flex flex-row justify-content-center">


            <div class="card" style="width: 80rem; margin: auto;"> <!-- Añadido margin: auto para centrar -->
                <form action="<?=BASE_URL?>modificarViaje/<?=$id_viaje?>" method="POST" class="row m-3 needs-validation" novalidate>
                    <div class="col-m-4">
                        <label for="validationCustom01" class="form-label">Destino de inicio</label>
                        <input type="text" class="form-control" id="validationCustom01" name="destino_inicio" required>
                    </div>
                    <div class="col-m-4">
                        <label for="validationCustom02" class="form-label">Destino de fin</label>
                        <input type="text" class="form-control" id="validationCustom02" name="destino_fin" required>

                    </div>
                    <div class="col-md-4">
                        <label for="validationCustomUsername" class="form-label">Fecha de viaje</label>
                        <div class="input-group has-validation">
                            <input type="date" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" name="fecha_salida" required>

                        </div>
                    </div>
                    <div class="col-md-3">
                        <label for="validationCustom03" class="form-label">Precio del viaje</label>
                        <input type="number" class="form-control" id="validationCustom03" name="precio" required>
                        <div class="invalid-feedback">
                            Please provide a valid city.
                        </div>
                    </div>
                    <select class="form-select m-2" aria-label="Default select example" name="id_pasajero">
                        <option selected>Seleccione</option>
                        <?php foreach ($pasajeros as $pasajero): ?>
                            <option value="<?= $pasajero->id_pasajero ?>"><?= $pasajero->nombre ?> <?= $pasajero->apellido;
                                                                                                endforeach ?> </option>


                    </select>

                    <div class="col-12 text-center mb-3">
                        <button class="btn btn-primary mt-3" type="submit">Agregar</button>
                    </div>
                </form>
            </div>
        </ul>
    </div>
</div>
<?php require 'templates/layout/pieDepagina.phtml' ?>