<?php require 'templates/layout/hedader.phtml'; ?>

<div class="container mt-5">
    <h1 class="text-center mb-4">Agregar Nuevo Viaje</h1>
    
    <div class="card">
        <div class="card-body">
            <form action="nuevo-viaje" method="POST" class="row g-3 needs-validation" novalidate>
                <div class="col-md-4">
                    <label for="validationCustom01" class="form-label">Destino de Inicio</label>
                    <input type="text" class="form-control" id="validationCustom01" name="destino_inicio" required>
                    <div class="invalid-feedback">Por favor, ingresa un destino de inicio válido.</div>
                </div>

                <div class="col-md-4">
                    <label for="validationCustom02" class="form-label">Destino de Fin</label>
                    <input type="text" class="form-control" id="validationCustom02" name="destino_fin" required>
                    <div class="invalid-feedback">Por favor, ingresa un destino de fin válido.</div>
                </div>

                <div class="col-md-4">
                    <label for="validationCustomUsername" class="form-label">Fecha de Viaje</label>
                    <input type="date" class="form-control" id="validationCustomUsername" name="fecha_salida" required>
                    <div class="invalid-feedback">Por favor, selecciona una fecha de viaje válida.</div>
                </div>

                <div class="col-md-3">
                    <label for="validationCustom03" class="form-label">Precio del Viaje</label>
                    <input type="number" class="form-control" id="validationCustom03" name="precio" required>
                    <div class="invalid-feedback">Por favor, ingresa un precio válido.</div>
                </div>

                <div class="col-md-4">
                    <label for="id_personas" class="form-label">Seleccionar Pasajero</label>
                    <select class="form-select" name="id_personas" id="id_personas" required>
                        <option selected disabled>Seleccione</option>
                        <?php foreach ($pasajeros as $pasajero): ?>
                            <option value="<?= $pasajero->id_pasajero ?>"><?= $pasajero->nombre ?> <?= $pasajero->apellido; ?></option>
                        <?php endforeach; ?>
                    </select>
                    <div class="invalid-feedback">Por favor, selecciona un pasajero.</div>
                </div>

                <div class="col-12 text-center">
                    <button class="btn btn-primary" type="submit">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require 'templates/layout/pieDepagina.phtml'; ?>
