<?php require 'templates/layout/hedader.phtml'; ?>

<div class="d-flex flex-row justify-content-center mb-4">
    <div class="p-2">
        <h1 class="display-6 text-center">Viajes Disponibles</h1>
    </div>
</div>

<div class="container m-5">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Nombre y Apellido</th>
                    <th>Destinos</th>
                    <th>Fecha Salida</th>
                    <th>Precio</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($viajes as $viaje): ?>
                    <tr>
                        <td><?= $persona->nombre ?> <?= $persona->apellido ?></td>
                        <td><a href="<?= BASE_URL ?>verMasViajes/<?= $viaje->id_viaje ?>" class="text-decoration-none"><?= $viaje->destino_inicio ?> a <?= $viaje->destino_fin ?></a></td>
                        <td><?= $viaje->fecha_salida; ?></td>
                        <td>$ <?= $viaje->precio ?> ARS</td>
                        <td>
                            <?php if (!empty($_SESSION['ID_USER'])): ?>
                                <div class="btn-group" role="group">
                                    <a href="<?= BASE_URL ?>eliminarViaje/<?= $viaje->id_viaje ?>" class="btn btn-outline-danger">Borrar</a>
                                    <a href="<?= BASE_URL ?>editarViaje/<?= $viaje->id_viaje ?>" class="btn btn-outline-success">Editar</a>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require 'templates/layout/pieDepagina.phtml'; ?>
