<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>VíaExpress</title>

</head>

<body class="cuerpo">
    <header>
        <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
            <div class="container-fluid">
                <!-- Marca de la navbar -->
                <a class="navbar-brand" href="#">Via Expres</a>

                <!-- Nombre del usuario, alineado a la derecha -->
                <?php if (!empty($_SESSION['ID_USER'])): ?>
                    <span class="navbar-text ms-auto text-white">
                        Bienvenido, <?= htmlspecialchars($_SESSION['USER_NAME']) ?>
                    </span>
                <?php endif; ?>


                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>listarViajes">Viajes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>mostrarPersonas">Pasajeros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= BASE_URL ?>login">Iniciar sesión</a>
                        </li>
                        <li class="nav-item">
                            <?php if (!empty($_SESSION['ID_USER'])): ?><a class="nav-link" href="cerrarSecion">Cerrar sesión</a><?php endif; ?>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        </div>
    </header>
    <main>