<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VíaExpress</title>

</head>

<body class="cuerpo">
    <header>
        <div class="logos">
        </div>
        <div class="boton-menu">
            <button id="boton-menu-js">≡</button>
            <nav class="barra-de-navegacion">
                <ul class="encabezado-de-la-pagina">
                    <li>
                        <button type="button" id="traer_inicio">Inicio</button>
                    </li>
                    <li>
                        <button type="button" id="traer_horario_cole">inicia secion</button>
                    </li>
                    <li>
                        <button type="button" id="traer_comodidad">lista</button>
                    </li>
                </ul>
            </nav>
        </div>
    </header>

    <main>