
</main>


<footer>
        <div class="contacto">
            <h4>Contacto</h4>
            <a href="https://mail.google.com/mail/u/0/?ogbl">Gmail</a>
            <p>0810-333-7575</p>
        </div>
        <div class="redes-sociales">
            <h4>Redes sociales</h4>
            <ul>
                <li><a href="https://www.instagram.com/">Instagram</a></li>
                <li><a href="https://www.facebook.com/?_rdr">Facebook</a></li>
            </ul>
        </div>
    </footer>
</body>

</html>