<?php require 'templates/layout/hedader.phtml' ?>

<div class="d-flex flex-row justify-content-center mb-4">
    <div class="p-2">
        <h1 class="display-6 text-center text-primary">Pasajeros</h1>
    </div>
</div>

<div class="container-fluid">
    <div class="table-responsive m-3"> 
        <table class="table table-striped table-hover w-100">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th class="text-center">Acciones</th>
                    <th>
                        <?php if (!empty($_SESSION['ID_USER'])): ?>
                            <a href="<?= BASE_URL ?>formularioPersona" class="btn btn-success btn-sm">Insertar</a>
                        <?php endif; ?>
                    </th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($personas as $persona): ?>
                    <tr>
                        <td><?= $persona->nombre ?></td>
                        <td><?= $persona->apellido ?></td>
                        <td class="text-center">
                            <?php if (!empty($_SESSION['ID_USER'])): ?>
                                <div class="btn-group" role="group">
                                    <a href="<?= BASE_URL ?>eliminarPersona/<?= $persona->id_pasajero ?>" class="btn btn-outline-danger btn-sm" title="Borrar pasajero">Borrar</a>
                                    <a href="<?= BASE_URL ?>mostrarFormEditPersona/<?= $persona->id_pasajero ?>" class="btn btn-outline-success btn-sm" title="Editar pasajero">Editar</a>
                                </div>
                            <?php endif; ?>
                        </td>
                        <td>
                            <a href="<?= BASE_URL ?>viajesPorPersonas/<?= $persona->id_pasajero ?>" class="btn btn-outline-primary btn-sm">Ver Viajes</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require 'templates/layout/pieDepagina.phtml' ?>
